### ISSUE TITLE
Résultat inattendu  lors de la récupération des templates_collector par le template_peer_id

### ISSUE THREAD

**Issue by bienvenuMN** [Givexpert/plugin-wordpress#1]
L'exécution de la route : template_collectors/?user=xxxxxxx&key=xxxxxx&template_peer_id=14 devrait renvoyer un tableau vide puisqu'il n'y à pas de donnée ayant un template_peer_id = 14.

La méthode exécuter pour la récupération de cette n'est donc pas fonctionnelle.

**Comment by anthonyfifre** [comment]
Corrigé
