### ISSUE TITLE
Problème de CORS lors des requêtes vers l'API

### ISSUE THREAD

**Issue by bienvenuMN** [Givexpert/plugin-wordpress#3]
Je rencontre aussi un problème de CORS lors de l'exécution des requêtes vers l'API.

**Comment by anthonyfifre** [comment]
Quel est l'erreur rencontrée ?

**Comment by bienvenuMN** [comment]
J'ai l'erreur suivante :

Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://2022-1.givexpert.org/api/template_collectors/?user=xxxxx&key=xxxxxx. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 200.

**Comment by anthonyfifre** [comment]
L'API n'a pas été prévue pour être attaquée en JS, cependant j'ai ajouté l'entête.

**Comment by bienvenuMN** [comment]
Ok, ça marche à présent.

Merci
